name: query-prismic-api
runs:
  using: 'node16'
  main: dist/index.js
inputs:
  ACCESS_TOKEN:
    description: should be a Prismic Access Token.
    required: true

  END_POINT:
    description: endpoint for Prismic.
    required: true

  QUERY:
    description: |
      add the query here. should be fully formatted, but caan contain double brackets for certain conditions.
      conditions should be formatted in double brackets like this: {{fn,value}}
      available conditions:
        {{date,offset}}: returns an offset of the current date
        
    requred: false
    default: ""

  FIELDS:
    description: |
      if blank will return entire object. fields should comma delimited and use dot notation to
      represent where in the response object the field is (i.e data.intro.title). Keys can aalso be
      added for the returned object in case they should have a different name (i.e title:data.intro.title).
      example: id:uid,data.intro.title,data.intro.location would return {id:123,title:hello,location:france}
    required: false

outputs:
  DATA:
    description: outputs a stringifyed json object
